export const cards = [

  {
    src: './images/Hogwarts Castle.png',
    name: 'Hogwarts Castle',
    price: '470',
    info: 'info1',
  },
  {
    src: './images/titanic.png',
    name: 'Titanic',
    price: '680',
    info: '110 years ago, shipbuilding history was made. After three years of the hard work of 15,000 people, the Titanic left the river Lagan in Belfast to begin its journey in Southampton. Nearly everything about the ship was a first. It was built in the biggest slipway of its time and even its center anchor was the largest ever forged, weighing in at 16 tonnes! It’s a story of determination, and here at The LEGO Group we’ve always been inspired by pioneers – by those who want to try harder, build bigger and test new waters. Which is why, 11 decades later, we’re paying tribute to one of history’s most important ships with one of our biggest LEGO sets ever created, the Titanic. At such a scale, it would almost be irresponsible of us not to lend a helping hand in how to display such an epic build! So, we’ve roped in some of our big-set-loving AFOLs (Adults Fans of LEGO) to help you with their top tips on how to display massive LEGO sets…',
  },
  {
    src: './images/spider-man.png',
    name: 'Spider-man',
    price: '35',
    info: 'Put Spider-Man action into the hands of fans aged 8 and up with the LEGO® Marvel Spider-Man Figure (76226). Standing over 9.5 in. (24 cm) tall, this buildable take-anywhere toy brings Marvel-movie authenticity to kids’ Super Hero adventures. A Spidey of their own!Based on Spider-Man from the Marvel Universe, this fully jointed figure is just like the real thing. Using the web accessories included, kids can move and position their Spider-Man as they battle their way through endless exciting missions. When the day’s web-slinging action is over, the flexible figure looks great on display. The free LEGO Building Instructions app lets kids view, zoom and rotate the model as they build, giving them an amazing sense of immersion and interaction during the construction process.',
  },
  {
    src: './images/venom.png',
    name: 'Venom',
    price: '30',
    info: 'info4',
  },
  {
    src: './images/Daily-Bugle.png',
    name: 'Daily Bugle',
    price: '330',
    info: 'info5',
  },
  {
    src: './images/future.png',
    name: 'Back to the future',
    price: '200',
    info: 'info6',
  },
  {
    src: './images/Bugatti.jpg',
    name: 'Bugatti',
    price: '350',
    info: 'info1',
  },
  {
    src: './images/truck.png',
    name: 'Truck',
    price: '160',
    info: 'This model is packed with pneumatic features and authentic details, making it ideal for role play.',
  },
  {
    src: './images/Hogwarts Castle.png',
    name: 'Hogwarts Castle',
    price: '470',
    info: 'info1',
  },
  {
    src: './images/titanic.png',
    name: 'Titanic',
    price: '680',
    info: 'info2',
  },
  {
    src: './images/spider-man.png',
    name: 'Spider-man',
    price: '35',
    info: 'info3',
  },
  {
    src: './images/venom.png',
    name: 'Venom',
    price: '30',
    info: 'info4',
  },
  {
    src: './images/Daily-Bugle.png',
    name: 'Daily Bugle',
    price: '330',
    info: 'info5',
  },
  {
    src: './images/future.png',
    name: 'Back to the future',
    price: '200',
    info: 'info6',
  },
  {
    src: './images/Bugatti.jpg',
    name: 'Bugatti',
    price: '350',
    info: 'info1',
  },
  {
    src: './images/truck.png',
    name: 'Truck',
    price: '160',
    info: 'This model is packed with pneumatic features and authentic details, making it ideal for role play.',
  },
  {
    src: './images/Hogwarts Castle.png',
    name: 'Hogwarts Castle',
    price: '470',
    info: 'info1',
  },
  {
    src: './images/titanic.png',
    name: 'Titanic',
    price: '680',
    info: 'info2',
  },
  {
    src: './images/spider-man.png',
    name: 'Spider-man',
    price: '35',
    info: 'info3',
  },
  {
    src: './images/venom.png',
    name: 'Venom',
    price: '30',
    info: 'info4',
  },
  {
    src: './images/Daily-Bugle.png',
    name: 'Daily Bugle',
    price: '330',
    info: 'info5',
  },
  {
    src: './images/future.png',
    name: 'Back to the future',
    price: '200',
    info: 'info6',
  },
  {
    src: './images/Bugatti.jpg',
    name: 'Bugatti',
    price: '350',
    info: 'info1',
  },
  {
    src: './images/truck.png',
    name: 'Truck',
    price: '160',
    info: 'This model is packed with pneumatic features and authentic details, making it ideal for role play.',
  },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 3',
  //   price: '300',
  //   info: 'info3',
  // },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 4',
  //   price: '400',
  //   info: 'info4',
  // },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 5',
  //   price: '500',
  //   info: 'info5',
  // },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 6',
  //   price: '600',
  //   info: 'info6',
  // },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 1',
  //   price: '100',
  //   info: 'info1',
  // },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 2',
  //   price: '200',
  //   info: 'info2',
  // },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 3',
  //   price: '300',
  //   info: 'info3',
  // },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 4',
  //   price: '400',
  //   info: 'info4',
  // },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 5',
  //   price: '500',
  //   info: 'info5',
  // },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 6',
  //   price: '600',
  //   info: 'info6',
  // },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 1',
  //   price: '100',
  //   info: 'info1',
  // },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 2',
  //   price: '200',
  //   info: 'info2',
  // },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 3',
  //   price: '300',
  //   info: 'info3',
  // },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 4',
  //   price: '400',
  //   info: 'info4',
  // },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 5',
  //   price: '500',
  //   info: 'info5',
  // },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 6',
  //   price: '600',
  //   info: 'info6',
  // },
]

export const productContainer = document.querySelector('.cards');
