const cards = [

  {
    src: './images/Hogwarts Castle.png',
    name: 'Hogwarts Castle',
    price: '470',
    info: 'info1',
  },
  {
    src: './images/titanic.png',
    name: 'Titanic',
    price: '680',
    info: 'info2',
  },
  {
    src: './images/spider-man.png',
    name: 'Spider-man',
    price: '35',
    info: 'info3',
  },
  {
    src: './images/venom.png',
    name: 'Venom',
    price: '30',
    info: 'info4',
  },
  {
    src: './images/Daily-Bugle.png',
    name: 'Daily Bugle',
    price: '330',
    info: 'info5',
  },
  {
    src: './images/future.png',
    name: 'Back to the future',
    price: '200',
    info: 'info6',
  },
  {
    src: './images/Bugatti.jpg',
    name: 'Bugatti',
    price: '350',
    info: 'info1',
  },
  {
    src: './images/truck.png',
    name: 'Truck',
    price: '160',
    info: 'This model is packed with pneumatic features and authentic details, making it ideal for role play.',
  },
  {
    src: './images/Hogwarts Castle.png',
    name: 'Hogwarts Castle',
    price: '470',
    info: 'info1',
  },
  {
    src: './images/titanic.png',
    name: 'Titanic',
    price: '680',
    info: 'info2',
  },
  {
    src: './images/spider-man.png',
    name: 'Spider-man',
    price: '35',
    info: 'info3',
  },
  {
    src: './images/venom.png',
    name: 'Venom',
    price: '30',
    info: 'info4',
  },
  {
    src: './images/Daily-Bugle.png',
    name: 'Daily Bugle',
    price: '330',
    info: 'info5',
  },
  {
    src: './images/future.png',
    name: 'Back to the future',
    price: '200',
    info: 'info6',
  },
  {
    src: './images/Bugatti.jpg',
    name: 'Bugatti',
    price: '350',
    info: 'info1',
  },
  {
    src: './images/truck.png',
    name: 'Truck',
    price: '160',
    info: 'This model is packed with pneumatic features and authentic details, making it ideal for role play.',
  },
  {
    src: './images/Hogwarts Castle.png',
    name: 'Hogwarts Castle',
    price: '470',
    info: 'info1',
  },
  {
    src: './images/titanic.png',
    name: 'Titanic',
    price: '680',
    info: 'info2',
  },
  {
    src: './images/spider-man.png',
    name: 'Spider-man',
    price: '35',
    info: 'info3',
  },
  {
    src: './images/venom.png',
    name: 'Venom',
    price: '30',
    info: 'info4',
  },
  {
    src: './images/Daily-Bugle.png',
    name: 'Daily Bugle',
    price: '330',
    info: 'info5',
  },
  {
    src: './images/future.png',
    name: 'Back to the future',
    price: '200',
    info: 'info6',
  },
  {
    src: './images/Bugatti.jpg',
    name: 'Bugatti',
    price: '350',
    info: 'info1',
  },
  {
    src: './images/truck.png',
    name: 'Truck',
    price: '160',
    info: 'This model is packed with pneumatic features and authentic details, making it ideal for role play.',
  },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 3',
  //   price: '300',
  //   info: 'info3',
  // },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 4',
  //   price: '400',
  //   info: 'info4',
  // },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 5',
  //   price: '500',
  //   info: 'info5',
  // },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 6',
  //   price: '600',
  //   info: 'info6',
  // },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 1',
  //   price: '100',
  //   info: 'info1',
  // },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 2',
  //   price: '200',
  //   info: 'info2',
  // },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 3',
  //   price: '300',
  //   info: 'info3',
  // },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 4',
  //   price: '400',
  //   info: 'info4',
  // },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 5',
  //   price: '500',
  //   info: 'info5',
  // },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 6',
  //   price: '600',
  //   info: 'info6',
  // },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 1',
  //   price: '100',
  //   info: 'info1',
  // },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 2',
  //   price: '200',
  //   info: 'info2',
  // },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 3',
  //   price: '300',
  //   info: 'info3',
  // },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 4',
  //   price: '400',
  //   info: 'info4',
  // },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 5',
  //   price: '500',
  //   info: 'info5',
  // },
  // {
  //   src: './images/2.jpg',
  //   name: 'Товар 6',
  //   price: '600',
  //   info: 'info6',
  // },
]

export default cards;